# Dependencies
markdown: redcarpet
highlighter: pygments
comments: true

# Permalinks
permalink: /blog/:year/:month/:day/:title

# Setup
title: Beerlington
tagline: The Blog
description: 'The Blog'
url: http://beerlington.com

author:
  name: 'Peter Brown'
  url: https://twitter.com/beerlington

paginate: 5
